name: Pull Request Checks

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: checks-${{ github.ref }}

permissions: {}

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: false

      - run: corepack enable
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
        with:
          node-version: "24"

      - run: pnpm install
      - run: pnpm check
      - run: pnpm lint
